### ISSUE TITLE
2 errors: Cannot Filter. The session is not yet started. Input string was not in a correct format.

### ISSUE THREAD

**Issue by KubaNet** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#102]
When using extension these errors are showing many times.

![Image](https://github.com/user-attachments/assets/8d9bbf09-bf62-4377-bab1-19d39934fbda)
![Image](https://github.com/user-attachments/assets/bb9e04bd-4d25-4f82-a2ac-c39323e7f857)

**Comment by theron-wang** [comment]
Both errors should be fixed in 1.10.1, but I wasn't able to confirm if the first error was indeed fixed. If it still persists, feel free to reopen the issue :)

**Comment by KubaNet** [comment]
@theron-wang did you see my comment? I can't reopen this issue..

**Comment by theron-wang** [comment]
Sorry, yes, I just haven’t had time to respond; I’ll try to get a fix over the weekend.

**Comment by theron-wang** [comment]
@KubaNet I wasn't able to reproduce any of these, unfortunately. If you would be able to provide a few more details, that would be greatly appreciated.

As a general note, could you provide your Tailwind version (3.x or 4.x, mainly)? Your theme configuration file would also be useful.

> 1. Second error (Input string..) still happens. But only when using Backspace when changing classes names. It doesn't appear when using Delete button.

Does this only occur in a specific type of file (i.e. `.css`, `.razor`, `.html`), or all of them? Does this occur when backspacing all classes, or just a select few?

> 2. There is also problem in css input file, when writing after `@apply` directive. It doubles what I write. For example when I want to write px it is ppxx.

This issue seems the most elusive - does this occur in all css files and in all contexts, or in very specific cases (i.e. at the end of a file/line)?

> 3. Also when I first build Tailwind the menu element changes to Stop Tailwind CSS JIT build process. Don't know what is that, but from this moment when I change input file it get build after saving it, but changes are not applied to output file. So have to stop it, build normally and it works. But everytime after first build it changes to JIT build process.

This is the default menu text for when you use the `Default` or `ManualJIT` build mode defined in your global extension settings. Since your files aren't updating, I would recommend turning on verbose building in Tools > Options > Tailwind CSS IntelliSense and attaching the build log here from the Build output window. You can also try changing the build mode to `OnSave`, since this avoids cli `--watch` (which is most likely what you are using right now) and allows the extension to run a build each time a file is saved instead. If all of these don't work, I would try to manually run the build process from cmd to rule out the possibility that it is a configuration issue.

I apologize for the inconvenience - if you could provide these details, that would be very helpful. Thanks.

**Comment by theron-wang** [comment]
@KubaNet I did some more digging and found that if the css configuration used custom colors with `var`, then the input string error would occur. This is fixed in 1.10.3, but I'm not sure if it's your specific issue.

**Comment by KubaNet** [comment]
@theron-wang yes, I have such a css input files with custom colors and `var`. So probably it is that.

**Comment by KubaNet** [comment]
> 2. There is also problem in css input file, when writing after @apply directive. It doubles what I write. For example when I want to write px it is ppxx.
This issue seems the most elusive - does this occur in all css files and in all contexts, or in very specific cases (i.e. at the end of a file/line)?

I am using Tailwind 4. Below is example css input where you can see when the doubling appear.

![Image](https://github.com/user-attachments/assets/6fc5fb6b-99d6-48de-bfb1-ecc8ae2fcc18)

**Comment by KubaNet** [comment]
> [@KubaNet](https://github.com/KubaNet) I did some more digging and found that if the css configuration used custom colors with `var`, then the input string error would occur. This is fixed in 1.10.3, but I'm not sure if it's your specific issue.

Unfortunately it is still happening - it occurs only in .razor files, not css files. Occurs also with clear configuration / input file (only with `@import "tailwindcss";`).

Is happens with my custom class names too, all class names. It will fire when I backspace some class name (from end or from middle, doesn't matter). Doesn't occur when I use delete instead of backspace. When using backspace again it doesn't appear, but after moving to another class name it happens again.

**Comment by theron-wang** [comment]
@KubaNet I still am unable to repro both of these issues. For the input string error, I tried removing all instances of `.Parse()` in this version, which could fix it. As for the double typing issue, I added a preventative measure to try to avoid this issue, but I have little confidence in it actually working. If you're able to, could you try to uninstall and reinstall the extension? Thanks - I'm sorry for these inconveniences.

**Comment by KubaNet** [comment]
@theron-wang as for now I don't get any error and double typing also is not appearing. So both my problems are corrected.

**Comment by theron-wang** [comment]
Great - I will close this as completed then. If it comes up again, please let me know!
